language: ruby
rvm:
  - 1.9.2
  - 2.1.2
  - jruby-19mode
  - rbx-2.2.7
env:
  - CODECLIMATE_REPO_TOKEN=2450a01d02d779c3b87f895eabeb9dd89971a57cc6922589931f60c238c7cbd6
notifications:
  email:
    - franceschini.romain@gmail.com
